"use client";

import Navbar from "./navbar";
import Footer from "./footer";
import { usePathname } from "next/navigation";

const Layout = ({ children }) => {
  const pathname = usePathname();
  const home = pathname !== "/";

  return (
    <>
      {home && <Navbar />}
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;

// import Navbar from "./Navbar";
// import Footer from "./Footer";

// const Layout = ({ children }) => {
//   return (
//     <html lang="en">
//       <body className="select-none">
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// };

// export default Layout;

// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="select-none">
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
